services:
  ministack:
    container_name: ministack
    image: ministackorg/ministack:latest
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=eu-west-2
      - PERSIST_STATE=1
      - STATE_DIR=/tmp/ministack-state
      - LAMBDA_EXECUTOR=docker
      - DOCKER_NETWORK=${COMPOSE_PROJECT_NAME:-ministack}_default
    volumes:
      - "${MINISTACK_VOLUME_DIR:-./volume}:/tmp/ministack-state"
      - "/var/run/docker.sock:/var/run/docker.sock"
    security_opt:
      - no-new-privileges:true
