principle_type: service
role_name: firstROLE
services:
  - ssm
  - ec2
  - iam
arn_ids:
  - devops
  - analytics
dev_principals:
  - type: AWS
    identifiers:
      - mySecondRole
  - type: Service
    identifiers:
      - cloudformation.amazonaws.com
pro_principals:
  - type: AWS
    identifiers:
      - ahhhhhPROD